### ISSUE TITLE
#/cart won't work with additional layouts?

### ISSUE THREAD

**Issue by 484-studio** [strapi/strapi-starter-nuxt-e-commerce#7] opened 2020-11-14 01:26 UTC
If I add additional layouts to my Nuxt file #/cart stops working and I can't work  out why?

I don't get any form of error in logs, and refreshing the #/cart page even seems to load. Clicking the add to cart button updates the URL but won't change the view.

**Comment by markkaylor** [comment] 2021-04-06 14:48
Hi @484-studio what do you mean your Nuxt file? You created a new layout in `/layouts` and then tried to use on a page as described here https://nuxtjs.org/docs/2.x/directory-structure/layouts/ ?  What are you trying to accomplish exactly with this new layout?   Could you provide steps to reproduce the problem?

**Comment by markkaylor** [comment] 2021-05-14 13:48
Hi @484-studio I'm not sure I reproduced your exact issue, but I created an additional layout and used it in a page.  When I navigated from my new layout to the default layout the the total price was missing from the cart.  If I refreshed, the price was back.  

As a workaround to this issue I moved:
```
<div hidden id="snipcart" data-api-key="<key>"></div>
```
From the default layout and the new layout I created.  I then put in the Navbar, since that component is shared between my two layouts and I assume is the same for you as well.  

```
  <button class="snipcart-checkout flex items-center">
    <Cart />
    <span class="snipcart-total-price ml-3 font-semibold text-sm text-indigo-500"></span>
    <div hidden id="snipcart" data-api-key="<key>"></div>
  </button>
```

This seemed to solve my issue. 

I am not sure we will make this change to the starter since it doesn't use multiple layouts.

I am closing this issue.  If this does not solve your problem, please re-open with detailed steps to reproduce or provide a github repo.

**Closed by markkaylor** 2021-05-14 13:48 UTC
Labels: status: pending reproduction
